{% set name = "dataprep" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0f12cafb4ca7dc4e8cc89c659315dc2bba6833807500ad4a252af542143d697c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - poetry >=1
  run:
    - aiohttp >=3.6,<4.0.0
    - bokeh >=2.0,<3
    - bottleneck >=1.3,<2.0
    - dask >=2.25,<3
    - cloudpickle >=0.2.2
    - fsspec >=0.6.0
    - toolz >=0.8.2
    - partd >=0.3.10
    - pyyaml
    - toolz >=0.8.2
    - ipywidgets >=7.5,<8.0
    - jinja2 >=2.11,<3.0
    - jsonpath-ng >=1.5,<2.0
    - nltk >=3.4,<4.0
    - numpy >=1.13.0,<2
    - pandas >=1,<2
    - pydantic >=1.6,<2.0
    - python >=3.6
    - regex >=2020.10.15,<2021.0.0
    - scipy >=1,<2
    - tqdm >=4.48,<5.0
    - wordcloud >=1.8,<2.0

test:
  imports:
    - dataprep
    - dataprep.assets
    - dataprep.clean
    - dataprep.connector
    - dataprep.connector.generator
    - dataprep.connector.schema
    - dataprep.datasets
    - dataprep.eda
    - dataprep.eda.basic
    - dataprep.eda.correlation
    - dataprep.eda.create_report
    - dataprep.eda.distribution
    - dataprep.eda.missing


about:
  home: https://github.com/sfu-db/dataprep
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Dataprep: Data Preparation in Python'
  doc_url: https://sfu-db.github.io/dataprep/
  dev_url: https://github.com/sfu-db/dataprep

extra:
  recipe-maintainers:
    - dovahcrow
